# Generated by Django 3.1.6 on 2021-03-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedstory', '0002_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='up_next_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='up_next_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='up_next_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
