# Generated by Django 3.1.6 on 2021-03-21 14:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, null=True)),
                ('img', models.TextField()),
                ('theme', models.CharField(max_length=200, null=True)),
                ('cta', models.CharField(max_length=200, null=True)),
                ('url', models.TextField()),
                ('p_img', models.TextField()),
                ('description_title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
