# Generated by Django 3.1.6 on 2021-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='hook',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
