# Generated by Django 3.1.6 on 2021-03-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_funnel_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='slug',
            field=models.SlugField(default='preview', unique=True),
            preserve_default=False,
        ),
    ]
