# Generated by Django 3.1.6 on 2021-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_headline', models.CharField(max_length=200, null=True)),
                ('ad_img', models.TextField(null=True)),
                ('ad_theme', models.CharField(max_length=200, null=True)),
                ('ad_hook', models.CharField(max_length=200, null=True)),
                ('ad_cta', models.CharField(max_length=200, null=True)),
                ('ad_url', models.TextField(null=True)),
            ],
        ),
    ]
