# Generated by Django 3.1.6 on 2021-03-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20210326_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdFunnel',
        ),
    ]
