# Generated by Django 3.1.6 on 2021-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_delete_adfunnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
