# Generated by Django 3.1.6 on 2021-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='slug',
            field=models.SlugField(default='discover', unique=True),
            preserve_default=False,
        ),
    ]
