# Generated by Django 3.1.6 on 2021-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_discover_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverpage',
            name='discover_img',
            field=models.TextField(),
        ),
    ]
