# Generated by Django 3.1.6 on 2021-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210321_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='topten',
            name='slug',
            field=models.SlugField(default='toptendicks', unique=True),
            preserve_default=False,
        ),
    ]
