# Generated by Django 3.1.6 on 2021-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_topten_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='slug',
            field=models.SlugField(default='hwy', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finance',
            name='slug',
            field=models.SlugField(default='hey', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='future',
            name='slug',
            field=models.SlugField(default='help', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hey', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productotd',
            name='slug',
            field=models.SlugField(default='hey', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='hey', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weview',
            name='slug',
            field=models.SlugField(default='hey', unique=True),
            preserve_default=False,
        ),
    ]
