# Generated by Django 3.1.6 on 2021-03-21 20:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210321_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='hey'),
            preserve_default=False,
        ),
    ]
