# Generated by Django 3.1.6 on 2021-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210322_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='about',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='about',
        ),
        migrations.RemoveField(
            model_name='discover',
            name='about',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='about',
        ),
        migrations.RemoveField(
            model_name='future',
            name='about',
        ),
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='about',
        ),
        migrations.RemoveField(
            model_name='video',
            name='about',
        ),
        migrations.RemoveField(
            model_name='weview',
            name='about',
        ),
    ]
