# Generated by Django 3.1.6 on 2021-03-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210322_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverpage',
            name='up_next_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discoverpage',
            name='up_next_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discoverpage',
            name='up_next_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
