# Generated by Django 3.1.6 on 2021-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, null=True)),
                ('img', models.TextField()),
                ('is_ad', models.BooleanField(default=False)),
                ('ad_url', models.CharField(max_length=200, null=True)),
                ('ad_cta', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
